"""speedMulti allow null

Revision ID: 58ab0275bad1
Revises: b3fcdde2ec28
Create Date: 2022-08-03 12:45:20.953943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ab0275bad1'
down_revision = 'b3fcdde2ec28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objecttypes', 'speedMultiplier',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objecttypes', 'speedMultiplier',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
